ALTER TABLE compras
ADD COLUMN valor_inss DECIMAL(10,2) DEFAULT 0,
ADD COLUMN valor_rat DECIMAL(10,2) DEFAULT 0,
ADD COLUMN valor_senar DECIMAL(10,2) DEFAULT 0,
ADD COLUMN valor_funrural DECIMAL(10,2) DEFAULT 0,
ADD COLUMN valor_frete DECIMAL(10,2) DEFAULT 0,
ADD COLUMN valor_gerencial DECIMAL(10,2) DEFAULT 0,
ADD COLUMN valor_media_gerencial DECIMAL(10,2) DEFAULT 0;